# Generated by Django 5.1.1 on 2024-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NginxLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        db_index=True, unpack_ipv4=True, verbose_name="IP Address"
                    ),
                ),
                ("date", models.DateTimeField(db_index=True, verbose_name="Date")),
                (
                    "method",
                    models.CharField(
                        db_index=True, max_length=12, verbose_name="HTTP Method"
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        db_index=True, max_length=8192, verbose_name="URI"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(db_index=True, verbose_name="HTTP Status"),
                ),
                ("bytes_sent", models.IntegerField(verbose_name="Bytes sent")),
            ],
            options={
                "verbose_name": "Nginx log record",
                "ordering": ("-date",),
            },
        ),
    ]
